-- require('gitsigns').setup {
--   debug_mode = true
--   signs = {
--     add          = { text = '┃' },
--     change       = { text = '┃' },
--     delete       = { text = '_' },
--     topdelete    = { text = '‾' },
--     changedelete = { text = '~' },
--     untracked    = { text = '┆' },
--   },
--   numhl = false,
--   linehl = false,
--   watch_gitdir = {
--     interval = 1000,
--     follow_files = true
--   },
--   diff_opts = {
--     internal = true
--   },
--   sign_priority = 6,
--   update_debounce = 100,
--   status_formatter = nil, -- Use default
--   word_diff = false,
-- }
